global using Microsoft.eCommerceOnContainers.BuildingBlocks.EventBus.Abstractions;
global using Microsoft.eCommerceOnContainers.BuildingBlocks.EventBus.Events;
global using static Microsoft.eCommerceOnContainers.BuildingBlocks.EventBus.InMemoryEventBusSubscriptionsManager;
global using System.Text.Json.Serialization;
